BackEndASP/Controllers/CardsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BackEndASP.ViewModels;
using DAL;

namespace BackEndASP.Controllers
{
    public class CardsController : Controller
    {
        private BankContext db = new BankContext();

        //[AjaxOnly] //Pour accepter uniquement les appels ajax
        // GET: Cards/Id avec ID l'id du compte courant (Deposit) sélectionné

        #region Liste des cartes d'un compte courant => Get : Cards/{id}
        public ActionResult Index(int? id)
        {
            ViewBag.IdDeposit = id;
            return View(db.Cards.Include("Deposit").Where(c => c.Deposit.AccountID == id).ToList());
        }
        #endregion

        #region Détails d'une carte de crédit ==> NON DISPONIBLE DANS NOTRE CAS ! A SUPPRIMER PLUS TARD
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Card card = db.Cards.Find(id);
            if (card == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdDeposit = id;
            return View(card);
        }
        #endregion

        #region Création D'une carte de crédit => Get: Cards/Create/{idcompte}
        public ActionResult Create(int? id, int idclient)
        {
            ViewBag.IdDeposit = id;
            ViewBag.IdClient = idclient;
            ViewBag.Url = System.Web.HttpContext.Current.Request.UrlReferrer;
            return View();
        }
        #endregion

        #region Sauvegarde de création d'une carte => Post : Cards/Create/{idcompte}
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CardId,NewtorkIssuer,CardNumber,SecurityCode,ExpirationDate")] Card card, int? id, int idclient)
        {
            if (ModelState.IsValid)
            {
                card.Deposit = db.Deposits.Find(id);
                db.Cards.Add(card);
                db.SaveChanges();
                TempData.Add("Create", "Success");
                return RedirectToAction("Details", "Accounts",new { id = idclient, typecompte = "Deposit", idCompte = id});
            }
            ViewBag.IdDeposit = id;
            return View("Create", card);
        }
        #endregion

        #region Modification d'une carte de crédit => Get : Cards/Edit/{idcard}/Account/{idcompte}/Client/{idclient}
        public ActionResult Edit(int? id, int idcompte, int idclient)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Card card = db.Cards.Include("Deposit").First(c => c.CardId == id);
            if (card == null)
            {
                return HttpNotFound();
            }
            TempData.Add("IdAccount",idcompte);
            TempData.Add("IdClient", idclient);
            return View(card);
        }
        #endregion

        #region Sauvegarde d'une modification d'une carte => Post : Cards/Edit/{idcard}
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( Card card, int? id, int idcompte, int idclient)
        {
            if (ModelState.IsValid)
            {
                db.Entry(card).State = EntityState.Modified;
                db.SaveChanges();
                TempData.Add("Edit", "Success");
                return RedirectToAction("Details","Accounts", new { id = idclient, typecompte = "Deposit", idcompte = idcompte});
            }
            return View(card);
        }
        #endregion

        #region Suppression d'une carte de crédit => Post : Cards/Delete/{idcard}
        [HttpPost]
        public ActionResult Delete(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Card card = db.Cards.Include("Deposit").First(c => c.CardId == id);
            if (card == null)
            {
                return HttpNotFound();
            }
            ViewBag.idCard = id;
            ViewBag.idCompte = card.Deposit.AccountID;
            ViewBag.idClient = card.Deposit.Client.PersonId;
            return PartialView("Delete" , card);
        }
        #endregion

        #region Confirmation de suppression d'une carte de crédit => Post : Cards/Delete/{idcard}
        [HttpPost, ActionName("DeleteCard")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id, int idCompte, int idClient)
        {
            Card card = db.Cards.Find(id);
            //ViewBag.AccountId = card.Deposit.AccountID;
            db.Cards.Remove(card);
            db.SaveChanges();
            TempData.Add("Delete", "Success");
            return RedirectToRoute("DetailsAccounts",new { id = idClient, typecompte = "Deposit", idcompte = idCompte });//("Index", new { id = ViewBag.AccountId } );
        }
        #endregion

        #region Dispose du controller Cards
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        #endregion
    }
}

BackEndASP/Views/Cards/Create.cshtml
@model DAL.Card

@{
    ViewBag.Title = "Ajouter une carte banquaire";
}

<h2>Ajouter une carte banquaire</h2>


@using (Html.BeginForm($"Account/{ViewBag.IdDeposit}/Create/{ViewBag.IdClient}", "Cards", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal well">
        <h4>Informations de la carte banquaire</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NewtorkIssuer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NewtorkIssuer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NewtorkIssuer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CardNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CardNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CardNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SecurityCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SecurityCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SecurityCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExpirationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExpirationDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExpirationDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Créer" class="btn btn-success" />
                <a href="@ViewBag.Url" class="btn btn-danger">
                    Annuler
                    <span class="glyphicon glyphicon-remove"></span>
                </a>
            </div>
            
        </div>
    </div>
}

<div>
    @*<span class="btn btn-danger">
        @Html.ActionLink("Annuler", "Index", "Cards", new { id = ViewBag.IdDeposit }, "")
    </span>*@
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BackEndASP/Views/Cards/Delete.cshtml
@model DAL.Card

@{
    ViewBag.Title = "Suppression d'une carte bancaire";
    Layout = null;
}
<div class="well">
    <h3>Supprimer cette carte bancaire?</h3>
    <div>
        @using (Html.BeginForm($"DeleteCard/{Model.CardId}/{ViewBag.IdCompte}/{ViewBag.IdClient}", "Cards", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(model => model.CardId)
            <div class="form-actions no-color">
                <button type="submit" class="btn btn-danger">
                    Supprimer
                    <span class="glyphicon glyphicon-trash"></span>
                </button>

                <button type="button" class="btn btn-success" data-dismiss="modal" onclick="CloseModalDel()">
                    Annuler
                    <span class="glyphicon glyphicon-remove"></span>
                </button>
            </div>
        }
    </div>
</div>

BackEndASP/Views/Cards/Details.cshtml
@model DAL.Card

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Card</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NewtorkIssuer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NewtorkIssuer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CardNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CardNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SecurityCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SecurityCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExpirationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExpirationDate)
        </dd>

    </dl>
</div>
<p>
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.CardId }) |*@
    @Html.ActionLink("Back to List", "Index", new { id = ViewBag.IdDeposit })
</p>

BackEndASP/Views/Cards/Edit.cshtml
@model DAL.Card

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm($"Edit/{Model.CardId}/Account/{TempData["IdAccount"]}/Client/{TempData["IdClient"]}", "Cards", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Card</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CardId)

        <div class="form-group">
            @Html.LabelFor(model => model.NewtorkIssuer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NewtorkIssuer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NewtorkIssuer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CardNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CardNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CardNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SecurityCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SecurityCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SecurityCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExpirationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExpirationDate, new { htmlAttributes = new { @class = "form-control",
           @Value = Model.ExpirationDate.ToString("yyyy-MM-dd")} })
                @Html.ValidationMessageFor(model => model.ExpirationDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-success">Sauvegarder <span class="glyphicon glyphicon-floppy-disk"></span></button>
                @*<input type="submit" value="Sauvegarder" class="btn btn-success">*@
            </div>
        </div>
    </div>
}

<div>
    <a class="btn btn-info" href="@Url.Action("Details","Accounts",new { id = TempData["IdClient"], typecompte = "Deposit", idcompte = TempData["IdAccount"]})"><span class="glyphicon glyphicon-arrow-left"></span> Retour </a>
    @*<span class="btn btn-danger">@Html.ActionLink("Retour à la liste", "Index", "Cards", new { id = ViewBag.IdDeposit }, "") </span>*@
    @*@Html.ActionLink("Back to List", "Index")*@
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BackEndASP/Views/Cards/Index.cshtml
@model BackEndASP.ViewModels.EditAccountViewModel
@*IEnumerable<DAL.Card>*@

@{
    ViewBag.Title = "Index";
}

@*Fenetre modale pour la confirmation de suppression*@
<div class="modal" id="myModals" style="display:none">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"
                        data-dismiss="modal" aria-label="Close" onclick="CloseModalDel()">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">Supprimer une carte bancaire</h4>
            </div>
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>

@if (Model.EditDeposit.Cards.Count > 0)
{

    <h2>Details des cartes du compte : </h2>

    <div class="well">
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.EditDeposit.Cards.Single().CardId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.EditDeposit.Cards.Single().CardNumber)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.EditDeposit.Cards.Single().SecurityCode)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.EditDeposit.Cards.Single().NewtorkIssuer)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model.EditDeposit.Cards)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.NewtorkIssuer)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CardNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SecurityCode)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ExpirationDate)
                    </td>
                    <td>
                        <div class="btn-group">
                            @using (Html.BeginForm($"Delete/{item.CardId}", "Cards", FormMethod.Post, new { @class = "FormDelCard btn-group" }))
                            {
                                <a class="btn btn-warning" href="@Url.Action($"Edit/{item.CardId}" +
                                                                $"/Account/{Model.EditDeposit.AccountID}/Client/{Model.PersonID}", "Cards")"
                                   data-toggle="tooltip" data-placement="bottom" title="Modifier la carte bancaire">
                                    <span class="glyphicon glyphicon-pencil"></span>
                                </a>

                                @Html.AntiForgeryToken()
                                @Html.HiddenFor(model => item.CardId, new { id = "idCard" })
                                @Html.HiddenFor(model => model.EditDeposit.AccountID)
                                @Html.HiddenFor(model => model.PersonID)

                                <button class="btn btn-danger Delete" type="submit" id="Delete"
                                        data-toggle="tooltip" data-placement="bottom" title="Supprimer la carte bancaire"><span class="glyphicon glyphicon-trash"></span></button>
                            }
                        </div>
                    </td>
                </tr>
            }

        </table>

        <div class="btn-group">
            <a href="@Url.Action("Create","Cards", new { id = Model.EditDeposit.AccountID, idclient = Model.PersonID })"
               class="btn btn-info">
                Ajouter une carte bancaire
                <span class="glyphicon glyphicon-plus"></span>
            </a>
        </div>
    </div>
}
else
{
    <h2>Détails des cartes du compte</h2>
    <div class="well">
        <div class="alert-danger badge"><h4>Aucune carte existe pour ce compte.</h4></div>
        <a href="@Url.Action("Create","Cards", new { id = Model.EditDeposit.AccountID, idclient = Model.PersonID })" class="btn btn-info">
            Ajouter une carte banquaire
            <span class="glyphicon glyphicon-plus">
            </span>
        </a>
    </div>
}
<div id="Edit" class="col-xs-12 alert-info" style="border-radius:20px; padding:30px; display:none;">

</div>

@*<a href="@Url.Action("Edit", "Cards", new { id = item.CardId })" class="btn btn-warning"><span class="glyphicon glyphicon-pencil"></span></a>
    @Html.ActionLink("Details", "Details", new { id = item.CardId }) |
    @Html.ActionLink("Delete", "Delete", new { id = item.CardId })
    <a href="@Url.Action("Delete", "Cards", new { id = item.CardId })" class="btn btn-danger"><span class="glyphicon glyphicon-remove-sign"></span></a>*@